### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by lopuhin** [scrapy/scrapy#2213]
It would be nice to enable pypy tests on travis, mention pypy support in the docs and benchmark a couple of spiders.

What is currently broken in tests:
- [x] #2030 - there are failing signals tests under PyPy (old signals also didn't work under PyPy) - probably it's better to fix them after the merge, since the PR is already big.
- [x] There are some failures with encoding (different number of <?> inserted), filed https://bitbucket.org/pypy/pypy/issues/2389/different-behavior-of-bytesdecode-utf8
- [x] Failure in `ImagesPipelineTestCase.test_convert_image` looks like a Pillow bug under PyPy?
- [x] There are some failures in tests that rely on implementations differences or bugs that are absent on PyPy - here just the tests must be updated.

Other tasks:
- [x] Test and document installation under PyPy (there can be more issues than for CPython due to missing or outdated binary wheels, e.g. https://github.com/pyca/cryptography/issues/2138)

Status: 1 failure in https://github.com/rootAvish/scrapy/compare/signal-rewrite...lopuhin:pypy?expand=1

**Comment by redapple** [comment]
@lopuhin , what do you think of adding PyPy build to Travis and adding it to allowed failures?

**Comment by lopuhin** [comment]
@redapple it's possible to do it now, but I'd rather do it after merge of #2030, unless we want to fix pypy issues in it before the merge. I think turning it on after #2030 is less work overall, because although that PR brings some failing tests, it still reduces overall number of pypy failures, including many crawler and spider tests.

**Comment by lopuhin** [comment]
@redapple I think I misunderstood you - "adding it to allowed failures" means we'll know the status of pypy tests, but the build will not fail if there are pypy failures? If that is correct then yes, I'm +1!

**Comment by redapple** [comment]
@lopuhin , correct, this will allow running the tests, monitor progress with PyPy, while still having the greenlight from Travis (assuming other Py2.7..Py3.5 tests pass)

**Comment by redapple** [comment]
Tentative: https://github.com/scrapy/scrapy/pull/2215

**Comment by lopuhin** [comment]
I checked speed on one CPU bound crawler, it was about 2x (or a little more) faster.

There were also a couple of small issues not covered with tests:
- if one of the middlewares fails to import, the exception is not printed with ``scrapy crawl`` command
- links with non-ascii domains fail:
```
    for link in self.le.extract_links(response):
  File "/Users/kostia/shub/scrapy/scrapy/linkextractors/lxmlhtml.py", line 111, in extract_links
    all_links.extend(self._process_links(links))
  File "/Users/kostia/shub/scrapy/scrapy/linkextractors/__init__.py", line 103, in _process_links
    link.url = canonicalize_url(urlparse(link.url))
  File "/Users/kostia/shub/scrapy/scrapy/utils/url.py", line 92, in canonicalize_url
    parse_url(url), encoding=encoding)
  File "/Users/kostia/shub/scrapy/scrapy/utils/url.py", line 47, in _safe_ParseResult
    netloc = parts.netloc.encode('idna')
  File ".../pypy/lib-python/2.7/encodings/idna.py", line 164, in encode
    result.append(ToASCII(label))
  File ".../pypy/lib-python/2.7/encodings/idna.py", line 76, in ToASCII
    label = nameprep(label)
  File ".../pypy/lib-python/2.7/encodings/idna.py", line 21, in nameprep
    newlabel.append(stringprep.map_table_b2(c))
  File "/Users/kostia/opt/pypy-c-jit-86635-77392ad26350-osx64/lib-python/2.7/stringprep.py", line 197, in map_table_b2
    b = unicodedata.normalize("NFKC", al)
TypeError: argument 2 must be unicode, not str
```

**Comment by redapple** [comment]
@lopuhin , what's the input for the non-ASCII domain test?

**Comment by redapple** [comment]
FYI, there's a stalled PR around link extraction and non-ASCII URLs: https://github.com/scrapy/scrapy/pull/1949

**Comment by lopuhin** [comment]
@redapple sorry for the delay: it turns out it's not limited to just PyPy, CPython 2.7 also has this issue:
```
from scrapy.linkextractors.lxmlhtml import LxmlLinkExtractor
le = LxmlLinkExtractor()
from scrapy.http.response.text import TextResponse
le.extract_links(TextResponse(
    url='http://example.com',
    body=b'<a href="http://афыва">foo</a>',
    encoding='utf8'))
```

And it looks that #1949 covers that, thanks for the pointer!

**Comment by kmike** [comment]
@lopuhin do you think it is possible to have it in Scrapy 1.5 release (which we'll try to do in 2017)?

**Comment by lopuhin** [comment]
I think we can announce PyPy support for 1.5: it is enabled on Travis, and AFAIK @sibiryakov uses it in production. I can also check again the state of PyPy 3.5 and lxml, and at least file the bug if it does not work. Do you have anything else in mind? The last bug we were discussing is not related to PyPy, it was a general Python 2 issue.

**Comment by kmike** [comment]
Sounds good! 

There are two unchecked TODO items in your issue description @lopuhin - are they resolved, or should we resolve them before the release?

**Comment by lopuhin** [comment]
@kmike the failure is already resolved (probably by Pillow), but docs are worth updating, that's a good catch! I can work on it before next Monday.

**Comment by kmike** [comment]
It looks like this is ready to be closed - any more pull requests @lopuhin? :)

**Comment by lopuhin** [comment]
I think it's done, thanks for quick review and fixes @kmike !

**Comment by lopuhin** [comment]
Meanwhile, pypy 5.10 was released https://morepypy.blogspot.ru/2017/12/pypy27-and-pypy35-v510-dual-release.html
